name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/ImageBox/ImageBox.csproj && dotnet restore samples/ImageBox.Sample/ImageBox.Sample.csproj && dotnet restore tests/ImageBox.Tests/ImageBox.Tests.csproj

      - name: Build
        run: dotnet build ImageBox.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test ImageBox.slnx --configuration Release --no-build
